services:
  laravel:
    build:
      context: ./fleet-mgt-api
      dockerfile: Dockerfile
      target: dev
    container_name: laravel_app
    user: "1000:1000"
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./fleet-mgt-api
        target: /var/www/html
    env_file:
      - ./fleet-mgt-api/.env
    depends_on:
      db:
        condition: service_healthy
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]

  react:
    build:
      context: ./fleet-mgt-frontend
      dockerfile: Dockerfile
      target: dev
    container_name: react_app
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./fleet-mgt-frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fleet_mgt_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: david1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "laravel", "-pdavid1"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer_app
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
